name: Image template

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ github.repository_owner }}/key4hep-images/${{ inputs.image }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./Docker/${{ inputs.image }}/${{ inputs.image }}
          file: ./Docker/${{ inputs.image }}/${{ inputs.image }}/Dockerfile
          build-args: |
            REPOSITORY=${{ github.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
